[package]
name = "lexorank"
version = "0.1.0"
authors = ["jdcaballerov <jdcaballerov@advisability.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
